### Get All Students
GET http://localhost:8080/students

### Add a New Student
POST http://localhost:8080/students
Content-Type: application/json

{
  "name": "Zane",
  "score": 95
}

### Wrong Score
POST http://localhost:8080/students
Content-Type: application/json

{
  "name": "ErrorUser",
  "score": 150
}

### Cleanup Students below __(Score)
DELETE http://localhost:8080/students?threshold=100

### Wrong Name
POST http://localhost:8080/students
Content-Type: application/json

{ "name": "", "score": 80 }

### Wrong Score (Negative)
POST http://localhost:8080/students
Content-Type: application/json

{ "name": "Zane", "score": -5 }

### Fuzzy Search by Name
GET http://localhost:8080/students/search?name=z

### Get top 10 students
GET http://localhost:8080/students/top?n=10

### get students by id
GET http://localhost:8080/students/

### count students between score range
GET http://localhost:8080/students/count?min=80&max=100

### get students by id (non-existing)
GET http://localhost:8080/students/abc

###